import './globals.css'
import { Inter } from 'next/font/google'
import Wrapper from '@/components/Wrapper/Wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Тестовое задание DK - Frontend',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {

  return (
    <html lang="en">
      <Wrapper>
        <body className={inter.className}>{children}</body>
      </Wrapper>
    </html>
  )
}

export default RootLayout