'use client'

import { useEffect } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { getAllPosts, getUsers } from '@/api'
import postsStore from '@/store/posts'
import paginationStore from '@/store/pagination'
import usersStore from '@/store/users'
import { observer } from 'mobx-react-lite'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Тестовое задание DK - Frontend',
  description: 'Generated by create next app',
}

const RootLayout = observer(({
  children,
}: {
  children: React.ReactNode
}) => {

  useEffect(() => {
    getAllPosts()
      .then(data => {
        paginationStore.setTotalCount(data.length)
        postsStore.setPosts(data)
      }
      )

    getUsers()
      .then(data => usersStore.setUsers(data))
  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
})

export default RootLayout